# Generated by Django 3.1.2 on 2020-12-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=600)),
                ('phone_number', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=700)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bookmart',
            name='book_desciption',
        ),
        migrations.AddField(
            model_name='bookmart',
            name='book_category',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Nonfiction', 'Nonfiction')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bookmart',
            name='book_description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookmart',
            name='book_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='bookmart',
            name='book_pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bookmart',
            name='book_published',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
