# Generated by Django 3.1.2 on 2020-12-11 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_customer_order_orderitem_product_transectiondetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='books',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.bookmart'),
        ),
        migrations.AddField(
            model_name='transectiondetails',
            name='books',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.bookmart'),
        ),
    ]
