# Generated by Django 3.1.2 on 2020-12-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_payment_expire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='expire_date',
            field=models.DateTimeField(null=True),
        ),
    ]
