# Generated by Django 3.1.2 on 2020-12-12 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_customerorders_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerbooks',
            old_name='books',
            new_name='book',
        ),
    ]
