# Generated by Django 3.1.2 on 2020-12-16 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20201216_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 16, 19, 31, 19, 557964)),
        ),
        migrations.AddField(
            model_name='order',
            name='package',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
