# Generated by Django 3.1.2 on 2020-12-16 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20201216_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='date_added',
            new_name='date_ordred',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 16, 20, 5, 50, 210341)),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='package',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 16, 20, 5, 50, 208343)),
        ),
    ]
