# Generated by Django 3.1.2 on 2020-12-16 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20201216_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorders',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 16, 20, 17, 38, 497642)),
        ),
        migrations.AlterField(
            model_name='order',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 16, 20, 17, 38, 487905)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 16, 20, 17, 38, 491894)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
