# Generated by Django 3.1.2 on 2020-12-16 15:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20201216_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorders',
            name='package',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='package',
        ),
        migrations.AlterField(
            model_name='customerorders',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 16, 21, 22, 5, 258404)),
        ),
        migrations.AlterField(
            model_name='order',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 16, 21, 22, 5, 256409)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 16, 21, 22, 5, 257405)),
        ),
        migrations.CreateModel(
            name='OrderPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.IntegerField(blank=True, default=0, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.order')),
            ],
        ),
    ]
