# Generated by Django 3.1.2 on 2020-12-16 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20201216_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorders',
            name='package',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customerorders',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 16, 21, 32, 17, 363807)),
        ),
        migrations.AlterField(
            model_name='order',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 16, 21, 32, 17, 362810)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 16, 21, 32, 17, 362810)),
        ),
    ]
