# Generated by Django 3.1.2 on 2020-12-16 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20201216_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorders',
            name='total_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customerorders',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 16, 22, 1, 5, 656996)),
        ),
        migrations.AlterField(
            model_name='order',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 16, 22, 1, 5, 652005)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 16, 22, 1, 5, 653999)),
        ),
    ]
