# Generated by Django 3.1.2 on 2020-12-16 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20201216_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbooks',
            name='order_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customerorders',
            name='order_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customerorders',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 16, 23, 15, 39, 958185)),
        ),
        migrations.AlterField(
            model_name='order',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 16, 23, 15, 39, 957188)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 16, 23, 15, 39, 957188)),
        ),
    ]
