# Generated by Django 3.1.2 on 2020-12-12 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201212_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorders',
            name='payment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.payment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='expire_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
