# Generated by Django 3.1.2 on 2020-12-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_payment_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expire_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
