# Generated by Django 3.1.2 on 2020-12-12 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20201212_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorders',
            name='books',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.bookmart'),
        ),
        migrations.AlterField(
            model_name='customerorders',
            name='payment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.payment'),
        ),
    ]
