# Generated by Django 3.1.2 on 2020-12-12 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_customerbooks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerbooks',
            name='order_id',
        ),
    ]
