# Generated by Django 3.1.2 on 2020-12-12 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0021_auto_20201212_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmart',
            name='customer',
        ),
        migrations.AlterField(
            model_name='bookmart',
            name='book_publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
